import SwiftUI

// =============================================================================
// MARK: - DriverAlertsView (Alert Center)
// -----------------------------------------------------------------------------
// History log of weather/road-impact alerts generated by the AlertEngine, plus
// a toggle to enable/disable local push notifications. Reached from the bell in
// the Maps tab toolbar and (optionally) the dashboard card.
// =============================================================================

struct DriverAlertsView: View {
    @ObservedObject private var engine = AlertEngine.shared

    var body: some View {
        ZStack {
            Color.spBackground.ignoresSafeArea()

            if engine.history.isEmpty {
                emptyState
            } else {
                List {
                    Section {
                        Toggle(isOn: Binding(
                            get: { engine.notificationsEnabled },
                            set: { engine.setNotificationsEnabled($0) }
                        )) {
                            Label("Push Notifications", systemImage: "bell.badge.fill")
                                .foregroundStyle(Color.spTextPrimary)
                        }
                        .tint(Color.spGold)
                    }
                    .listRowBackground(Color.spCardBg)

                    Section("History") {
                        ForEach(engine.history) { alert in
                            AlertRow(alert: alert)
                                .listRowBackground(Color.spCardBg)
                        }
                    }
                }
                .scrollContentBackground(.hidden)
            }
        }
        .navigationTitle("Alert Center")
        .navigationBarTitleDisplayMode(.inline)
        .toolbar {
            if !engine.history.isEmpty {
                ToolbarItem(placement: .topBarTrailing) {
                    Button(role: .destructive) {
                        engine.clearHistory()
                    } label: {
                        Text("Clear").foregroundStyle(Color.spDanger)
                    }
                }
            }
        }
    }

    private var emptyState: some View {
        VStack(spacing: 14) {
            Image(systemName: "checkmark.shield.fill")
                .font(.system(size: 48))
                .foregroundStyle(Color.spSuccess)
            Text("No active alerts")
                .font(.headline)
                .foregroundStyle(Color.spTextPrimary)
            Text("Weather and road-impact warnings near your truck will appear here.")
                .font(.subheadline)
                .foregroundStyle(Color.spTextSecondary)
                .multilineTextAlignment(.center)
                .padding(.horizontal, 40)

            Toggle(isOn: Binding(
                get: { engine.notificationsEnabled },
                set: { engine.setNotificationsEnabled($0) }
            )) {
                Label("Push Notifications", systemImage: "bell.badge.fill")
                    .foregroundStyle(Color.spTextPrimary)
            }
            .tint(Color.spGold)
            .padding(.horizontal, 40)
            .padding(.top, 8)
        }
    }
}

private struct AlertRow: View {
    let alert: DriverAlert

    var body: some View {
        HStack(alignment: .top, spacing: 12) {
            Image(systemName: alert.category.systemImage)
                .font(.title3)
                .foregroundStyle(alert.severity.color)
                .frame(width: 28)

            VStack(alignment: .leading, spacing: 3) {
                HStack(spacing: 6) {
                    Text(alert.title)
                        .font(.subheadline.weight(.bold))
                        .foregroundStyle(Color.spTextPrimary)
                    Text(alert.severity.label.uppercased())
                        .font(.system(size: 9, weight: .bold))
                        .foregroundStyle(.white)
                        .padding(.horizontal, 6)
                        .padding(.vertical, 2)
                        .background(alert.severity.color, in: Capsule())
                }
                Text(alert.message)
                    .font(.caption)
                    .foregroundStyle(Color.spTextSecondary)
                HStack(spacing: 6) {
                    if let place = alert.placeName {
                        Text(place)
                        Text("·")
                    }
                    Text(alert.createdAt, style: .relative) + Text(" ago")
                }
                .font(.system(size: 10))
                .foregroundStyle(Color.spTextSecondary)
            }
        }
        .padding(.vertical, 4)
    }
}
