import UIKit

// =============================================================================
// MARK: - CPAPDFGenerator
// =============================================================================
//
// Renders a professional black-and-white CPA-ready PDF using UIKit's
// `UIGraphicsPDFRenderer`. Deliberately NO third-party PDF library — the
// output is plain Letter-size pages with monospaced accounting tables and a
// minimal serif header, so it reads like a real-world accountant deliverable.
//
// Layout:
//   Page 1  Header / Business Info / Tax Year / Expense Summary
//           Category Totals (full table)
//   Page 2+ Monthly Breakdown, Mileage Summary, Fuel Summary,
//           Top Expense Categories, Net Revenue Estimate
//   Final   Footer: "Generated by Sacred Pathway Driver Hub"
//
// Auto-paginates: each `drawSection` call checks `currentY` against the
// page bottom margin and starts a new page if needed. Tables are drawn
// row-by-row so even 200+ expense lines render correctly across pages.
// =============================================================================

enum CPAPDFGenerator {

    // US Letter @ 72dpi.
    private static let pageWidth: CGFloat = 612
    private static let pageHeight: CGFloat = 792
    private static let margin: CGFloat = 48
    private static let usableWidth: CGFloat = pageWidth - margin * 2

    // Reusable fonts (regular system + monospaced for accounting tables).
    private static let titleFont = UIFont.systemFont(ofSize: 22, weight: .bold)
    private static let h1Font    = UIFont.systemFont(ofSize: 15, weight: .bold)
    private static let h2Font    = UIFont.systemFont(ofSize: 12, weight: .semibold)
    private static let bodyFont  = UIFont.systemFont(ofSize: 10)
    private static let smallFont = UIFont.systemFont(ofSize: 9, weight: .regular)
    private static let monoFont  = UIFont.monospacedSystemFont(ofSize: 9.5, weight: .regular)
    private static let monoBold  = UIFont.monospacedSystemFont(ofSize: 9.5, weight: .semibold)

    // MARK: - Entry point

    static func render(package pkg: CPAExportPackage) throws -> Data {
        let rect = CGRect(x: 0, y: 0, width: pageWidth, height: pageHeight)
        let renderer = UIGraphicsPDFRenderer(bounds: rect,
                                             format: UIGraphicsPDFRendererFormat())

        return renderer.pdfData { ctx in
            var state = PageState(context: ctx, pageNumber: 1)
            ctx.beginPage()

            drawHeader(pkg: pkg, state: &state)
            drawBusinessInfo(pkg: pkg, state: &state)
            drawExpenseSummary(pkg: pkg, state: &state)
            drawCategoryTotals(pkg: pkg, state: &state)
            drawMonthlyBreakdown(pkg: pkg, state: &state)
            drawMileageSummary(pkg: pkg, state: &state)
            drawFuelSummary(pkg: pkg, state: &state)
            drawTopCategories(pkg: pkg, state: &state)
            drawWriteOffSummary(pkg: pkg, state: &state)
            if pkg.toggles.brokerPayments && !pkg.brokerPayments.isEmpty {
                drawBrokerPayments(pkg: pkg, state: &state)
            }
            drawNetRevenue(pkg: pkg, state: &state)
            drawFooterOnAllPages(state: &state)
        }
    }

    // MARK: - Per-page state

    private struct PageState {
        let context: UIGraphicsPDFRendererContext
        var pageNumber: Int
        var y: CGFloat = margin

        /// Page bottom limit before forced page break (leaves room for footer).
        var bottomLimit: CGFloat { pageHeight - margin - 24 }

        mutating func ensureRoom(_ heightNeeded: CGFloat) {
            if y + heightNeeded > bottomLimit {
                context.beginPage()
                pageNumber += 1
                y = margin
            }
        }
    }

    // MARK: - Sections

    private static func drawHeader(pkg: CPAExportPackage, state: inout PageState) {
        // Title line
        drawText("CPA READY TAX PACKAGE",
                 at: CGPoint(x: margin, y: state.y),
                 font: titleFont, color: .black)
        state.y += 28

        // Tagline
        drawText("Generated for accountant / tax-prep use.",
                 at: CGPoint(x: margin, y: state.y),
                 font: smallFont, color: .darkGray)
        state.y += 12

        // Horizontal rule
        drawRule(state: &state)
        state.y += 8
    }

    private static func drawBusinessInfo(pkg: CPAExportPackage, state: inout PageState) {
        state.ensureRoom(80)

        drawText("BUSINESS INFORMATION", at: CGPoint(x: margin, y: state.y),
                 font: h1Font, color: .black)
        state.y += 18

        let lines: [(String, String)] = [
            ("Carrier:",     pkg.companyName),
            ("MC#:",         pkg.mcNumber ?? "—"),
            ("DOT#:",        pkg.dotNumber ?? "—"),
            ("Period:",      pkg.preset.displayName),
            ("Date range:",  formatRange(pkg.dateRange)),
            ("Generated:",   formatDateTime(pkg.generatedAt)),
            ("Tax year:",    "\(Calendar.iso8601US.component(.year, from: pkg.dateRange.upperBound))"),
        ]
        for (k, v) in lines {
            drawKV(k, v, state: &state)
        }
        state.y += 12
    }

    private static func drawExpenseSummary(pkg: CPAExportPackage, state: inout PageState) {
        state.ensureRoom(80)
        drawText("EXPENSE SUMMARY", at: CGPoint(x: margin, y: state.y),
                 font: h1Font, color: .black)
        state.y += 18

        drawKV("Total revenue:",  money(pkg.totalRevenue), state: &state)
        drawKV("Total expenses:", money(pkg.totalExpenses), state: &state)
        drawKV("Net revenue (est.):", money(pkg.netRevenue), state: &state, bold: true)
        state.y += 12
    }

    private static func drawCategoryTotals(pkg: CPAExportPackage, state: inout PageState) {
        guard !pkg.categoryTotals.isEmpty else { return }
        state.ensureRoom(80)
        drawText("CATEGORY TOTALS", at: CGPoint(x: margin, y: state.y),
                 font: h1Font, color: .black)
        state.y += 18

        // Monospaced table: Category | Schedule C hint | Count | Total
        let columns: [Column] = [
            Column(title: "CATEGORY",      width: 150, align: .left),
            Column(title: "SCHEDULE C",    width: 220, align: .left),
            Column(title: "COUNT",         width: 50,  align: .right),
            Column(title: "TOTAL",         width: usableWidth - 150 - 220 - 50,
                   align: .right),
        ]
        drawTableHeader(columns: columns, state: &state)
        for ct in pkg.categoryTotals {
            state.ensureRoom(14)
            drawTableRow([
                ct.category.displayName,
                ct.category.scheduleCLineHint,
                "\(ct.count)",
                money(ct.total),
            ], columns: columns, state: &state)
        }
        state.y += 12
    }

    private static func drawMonthlyBreakdown(pkg: CPAExportPackage, state: inout PageState) {
        guard !pkg.monthlyBreakdown.isEmpty else { return }
        state.ensureRoom(80)
        drawText("MONTHLY BREAKDOWN", at: CGPoint(x: margin, y: state.y),
                 font: h1Font, color: .black)
        state.y += 18

        let columns: [Column] = [
            Column(title: "MONTH",     width: 160, align: .left),
            Column(title: "REVENUE",   width: 130, align: .right),
            Column(title: "EXPENSES",  width: 130, align: .right),
            Column(title: "NET",       width: usableWidth - 160 - 130 - 130,
                   align: .right),
        ]
        drawTableHeader(columns: columns, state: &state)
        for m in pkg.monthlyBreakdown {
            state.ensureRoom(14)
            drawTableRow([
                m.displayLabel,
                money(m.revenue),
                money(m.expenses),
                money(m.net),
            ], columns: columns, state: &state)
        }
        state.y += 12
    }

    private static func drawMileageSummary(pkg: CPAExportPackage, state: inout PageState) {
        guard pkg.toggles.mileageSummary else { return }
        state.ensureRoom(80)
        drawText("MILEAGE SUMMARY", at: CGPoint(x: margin, y: state.y),
                 font: h1Font, color: .black)
        state.y += 18

        drawKV("Loaded miles:",   number(pkg.mileage.loadedMiles),  state: &state)
        drawKV("Deadhead miles:", number(pkg.mileage.deadheadMiles), state: &state)
        drawKV("Total miles:",    number(pkg.mileage.totalMiles),    state: &state, bold: true)
        drawKV("IRS standard rate:",
               String(format: "$%.2f/mi", CPAMileageSummary.irsStandardRatePerMile),
               state: &state)
        drawKV("Estimated deduction (mi × rate):",
               money(pkg.mileage.estimatedStandardDeduction), state: &state, bold: true)
        state.y += 8
        drawText("Note: actual / standard-mileage method must be chosen consistently per vehicle. " +
                 "Review with your CPA.",
                 at: CGPoint(x: margin, y: state.y),
                 font: smallFont, color: .darkGray, maxWidth: usableWidth)
        state.y += 18
    }

    private static func drawFuelSummary(pkg: CPAExportPackage, state: inout PageState) {
        guard pkg.toggles.fuel else { return }
        state.ensureRoom(80)
        drawText("FUEL SUMMARY", at: CGPoint(x: margin, y: state.y),
                 font: h1Font, color: .black)
        state.y += 18

        drawKV("Gallons purchased:", number(pkg.fuel.gallons),  state: &state)
        drawKV("Total fuel cost:",   money(pkg.fuel.totalCost), state: &state)
        drawKV("Avg price/gallon:",
               String(format: "$%.3f", pkg.fuel.avgPricePerGallon), state: &state)
        if pkg.fuel.defGallons > 0 {
            drawKV("DEF gallons:",    number(pkg.fuel.defGallons), state: &state)
            drawKV("DEF cost:",       money(pkg.fuel.defCost),     state: &state)
        }
        state.y += 12
    }

    private static func drawTopCategories(pkg: CPAExportPackage, state: inout PageState) {
        guard !pkg.topCategories.isEmpty else { return }
        state.ensureRoom(80)
        drawText("TOP EXPENSE CATEGORIES", at: CGPoint(x: margin, y: state.y),
                 font: h1Font, color: .black)
        state.y += 18
        for (idx, ct) in pkg.topCategories.enumerated() {
            state.ensureRoom(14)
            let pct = pkg.totalExpenses > 0
                ? (ct.total / pkg.totalExpenses) * 100 : 0
            drawTableRow([
                "\(idx + 1).  \(ct.category.displayName)",
                money(ct.total),
                String(format: "%.1f%%", pct),
            ], columns: [
                Column(title: "", width: 320, align: .left),
                Column(title: "", width: 110, align: .right),
                Column(title: "", width: usableWidth - 320 - 110, align: .right),
            ], state: &state)
        }
        state.y += 12
    }

    private static func drawWriteOffSummary(pkg: CPAExportPackage, state: inout PageState) {
        state.ensureRoom(110)
        drawText("WRITE-OFF SUMMARY", at: CGPoint(x: margin, y: state.y),
                 font: h1Font, color: .black)
        state.y += 18

        func total(forCategories cats: [CPAExpenseCategory]) -> Double {
            pkg.categoryTotals
                .filter { cats.contains($0.category) }
                .reduce(0) { $0 + $1.total }
        }
        let fuelTotal       = total(forCategories: [.fuel, .def])
        let maintenanceTotal = total(forCategories: [.maintenance, .repair])
        let tollsTotal      = total(forCategories: [.tolls, .parking])
        let insuranceTotal  = total(forCategories: [.insurance])

        drawKV("Total fuel + DEF:",        money(fuelTotal), state: &state)
        drawKV("Total maintenance/repair:", money(maintenanceTotal), state: &state)
        drawKV("Total tolls + parking:",   money(tollsTotal), state: &state)
        drawKV("Total insurance:",         money(insuranceTotal), state: &state)
        state.y += 12
    }

    private static func drawBrokerPayments(pkg: CPAExportPackage, state: inout PageState) {
        state.ensureRoom(80)
        drawText("BROKER PAYMENTS", at: CGPoint(x: margin, y: state.y),
                 font: h1Font, color: .black)
        state.y += 18

        let columns: [Column] = [
            Column(title: "BROKER",   width: 320, align: .left),
            Column(title: "LOADS",    width: 70,  align: .right),
            Column(title: "REVENUE",  width: usableWidth - 320 - 70, align: .right),
        ]
        drawTableHeader(columns: columns, state: &state)
        for b in pkg.brokerPayments.prefix(40) {  // cap so we don't run away
            state.ensureRoom(14)
            drawTableRow([
                b.brokerName,
                "\(b.loadCount)",
                money(b.totalPaid),
            ], columns: columns, state: &state)
        }
        state.y += 12
    }

    private static func drawNetRevenue(pkg: CPAExportPackage, state: inout PageState) {
        state.ensureRoom(80)
        drawRule(state: &state)
        state.y += 8
        drawText("NET REVENUE ESTIMATE",
                 at: CGPoint(x: margin, y: state.y),
                 font: h1Font, color: .black)
        state.y += 18
        drawKV("Revenue:",   money(pkg.totalRevenue),  state: &state)
        drawKV("Expenses:",  money(pkg.totalExpenses), state: &state)
        drawKV("Net (est.):", money(pkg.netRevenue),   state: &state, bold: true)
        state.y += 14

        drawText("This report is informational only and does NOT constitute tax advice. " +
                 "Final filings should be reviewed and signed by a licensed CPA.",
                 at: CGPoint(x: margin, y: state.y),
                 font: smallFont, color: .darkGray, maxWidth: usableWidth)
        state.y += 28
    }

    private static func drawFooterOnAllPages(state: inout PageState) {
        // Drawn on the LAST page; auto-paginate uses ensureRoom so we just
        // stamp once at the very end. Simpler than retrofitting per-page
        // footers, and matches the IFTA / Settlement PDF conventions in the
        // rest of the app.
        let footerY = pageHeight - margin - 8
        drawText("Generated by Sacred Pathway Driver Hub  ·  sacredpathway.org",
                 at: CGPoint(x: margin, y: footerY),
                 font: smallFont, color: .gray, maxWidth: usableWidth)
    }

    // MARK: - Table primitives

    private struct Column {
        let title: String
        let width: CGFloat
        let align: NSTextAlignment
    }

    private static func drawTableHeader(columns: [Column], state: inout PageState) {
        state.ensureRoom(18)
        var x = margin
        for col in columns {
            drawTableCell(text: col.title, x: x, y: state.y,
                          width: col.width, align: col.align, bold: true)
            x += col.width
        }
        state.y += 13
        // Underline header
        let path = UIBezierPath()
        path.move(to: CGPoint(x: margin, y: state.y))
        path.addLine(to: CGPoint(x: margin + usableWidth, y: state.y))
        UIColor.black.setStroke()
        path.lineWidth = 0.5
        path.stroke()
        state.y += 4
    }

    private static func drawTableRow(_ values: [String], columns: [Column],
                                     state: inout PageState) {
        var x = margin
        for (i, col) in columns.enumerated() {
            let value = i < values.count ? values[i] : ""
            drawTableCell(text: value, x: x, y: state.y,
                          width: col.width, align: col.align, bold: false)
            x += col.width
        }
        state.y += 13
    }

    private static func drawTableCell(text: String,
                                      x: CGFloat, y: CGFloat,
                                      width: CGFloat,
                                      align: NSTextAlignment,
                                      bold: Bool) {
        let para = NSMutableParagraphStyle()
        para.alignment = align
        para.lineBreakMode = .byTruncatingTail
        let attrs: [NSAttributedString.Key: Any] = [
            .font: bold ? monoBold : monoFont,
            .foregroundColor: UIColor.black,
            .paragraphStyle: para,
        ]
        let rect = CGRect(x: x, y: y, width: width, height: 12)
        (text as NSString).draw(in: rect, withAttributes: attrs)
    }

    // MARK: - Key/value (label : value) row helper

    private static func drawKV(_ key: String, _ value: String,
                               state: inout PageState, bold: Bool = false) {
        state.ensureRoom(14)
        let keyAttrs: [NSAttributedString.Key: Any] = [
            .font: bold ? h2Font : bodyFont,
            .foregroundColor: UIColor.black,
        ]
        let valAttrs: [NSAttributedString.Key: Any] = [
            .font: bold ? monoBold : monoFont,
            .foregroundColor: UIColor.black,
        ]
        (key as NSString).draw(at: CGPoint(x: margin, y: state.y),
                               withAttributes: keyAttrs)

        let valSize = (value as NSString).size(withAttributes: valAttrs)
        let valX = margin + usableWidth - valSize.width
        (value as NSString).draw(at: CGPoint(x: valX, y: state.y),
                                 withAttributes: valAttrs)
        state.y += 14
    }

    // MARK: - Drawing primitives

    private static func drawText(_ text: String,
                                 at point: CGPoint,
                                 font: UIFont,
                                 color: UIColor,
                                 maxWidth: CGFloat? = nil) {
        let attrs: [NSAttributedString.Key: Any] = [
            .font: font,
            .foregroundColor: color,
        ]
        if let maxWidth {
            let rect = CGRect(x: point.x, y: point.y,
                              width: maxWidth, height: 40)
            (text as NSString).draw(in: rect, withAttributes: attrs)
        } else {
            (text as NSString).draw(at: point, withAttributes: attrs)
        }
    }

    private static func drawRule(state: inout PageState) {
        let path = UIBezierPath()
        path.move(to: CGPoint(x: margin, y: state.y))
        path.addLine(to: CGPoint(x: margin + usableWidth, y: state.y))
        UIColor.black.setStroke()
        path.lineWidth = 0.75
        path.stroke()
    }

    // MARK: - Formatters (file-private)

    private static func money(_ v: Double) -> String {
        let f = NumberFormatter()
        f.numberStyle = .currency
        f.locale = Locale(identifier: "en_US")
        f.maximumFractionDigits = 2
        return f.string(from: NSNumber(value: v)) ?? String(format: "$%.2f", v)
    }

    private static func number(_ v: Double) -> String {
        let f = NumberFormatter()
        f.numberStyle = .decimal
        f.maximumFractionDigits = 0
        return f.string(from: NSNumber(value: v)) ?? "\(Int(v))"
    }

    private static func formatRange(_ r: ClosedRange<Date>) -> String {
        let f = DateFormatter()
        f.dateStyle = .medium
        return "\(f.string(from: r.lowerBound)) → \(f.string(from: r.upperBound))"
    }

    private static func formatDateTime(_ d: Date) -> String {
        let f = DateFormatter()
        f.dateStyle = .medium
        f.timeStyle = .short
        return f.string(from: d)
    }
}
